### ISSUE TITLE
大地图支持

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#187]
现在H5样板V2.x版本只剩下大地图支持。
目前大地图有两种方案：

方案1：**直接画布大小为整个地图大小，然后调整可视窗口范围（平移）来进行有选择绘制。**

- 优点：实现较为简单
- 缺点：对性能要求较高；如果地图范围很大（比如30x30等），画布可达1000*1000，可能会导致内存问题，或会使得运行速度变慢。

方案2：**画布大小固定15x15，走路时正常窗口平移，每一步走完后立刻进行重绘。**

- 优点：性能较好
- 缺点：实现相对较为复杂，而且容易出现各种问题

目前暂定方案1实现。

@zhaouv @fux4

**Comment by ckcz123** [comment]
目前想法是基于黄鸡的试验品 #188 来做
需要额外支持的几个地方：
[ ] 显伤
[ ] 大地图的事件
[ ] 事件让勇士移动/跳跃
[ ] 自动寻路的绘制
[ ] 瞬间移动的支持
[ ] 道具：对称飞、上下楼器等
[ ] 缩略图绘制
[ ] 地图编辑器的支持

**Comment by zhaouv** [comment]
editor :
+ [x] 界面的兼容
+ [x] viewport调整以及对应的按钮, 地图两边的坐标刻度跟随
+ [ ] drawEventBlock, exportMap, formatMap 等对于的大地图的支持
+ [ ] 创建新的大地图, 长和宽的输入和检查
+ [ ] editor-mobile

**Comment by ckcz123** [comment]
Finished V2.4 #198
