### ISSUE TITLE
localStorage存储空间限制的突破

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#199]
由于现在localStorage只有5M空间大小，导致一旦塔多了就会出现内存不足的情况。
要想办法解决这个问题，例如尽量使用WebSQL或IndexedDB。

- 兼容性：对于不支持的浏览器能fallback回localStorage
- 垃圾存档清理工具的兼容

**Comment by zhaouv** [comment]
IndexedDB兼容性似乎更好,并且web SQL已被排出html5规范  
https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API  
https://caniuse.com/#feat=indexeddb

**Comment by ckcz123** [comment]
可以直接基于现成的第三方库 [localForage](https://github.com/localForage/localForage/) 来做。
该库同时对IndexedDB和WebSQL提供了类localStorage的key-value支持，同时对不支持的浏览器能fallback回localStorage。

一个问题是，IndexedDB和WebSQL的查询都是异步的，考虑到兼容性问题：
 - 对于即时存储值（如bool，int之类的值），直接存localStorage，这样能同步的设置和返回。
 - 对于存档，使用localForage进行存储到IndexedDB或WebSQL，并使用回调函数来完成下一步的操作（如读档、下载等）。

**Comment by ckcz123** [comment]
Finished #203
