### ISSUE TITLE
魔塔服务器相关

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#22]
此issue将讨论有关魔塔服务器，URL短链等问题，以方便H5魔塔的进一步推广。

**Comment by zhaouv** [comment]
mota.pw

**Comment by zhaouv** [comment]
游戏人数，人气，以及评分、评论等

通关时直接提问“你想记录名字吗”
如果确认，则prompt弹出一个框让用户输入自己的ID
post就开始游戏时记一下人次；通关时时记一下MAX数据

最后游戏时间

**Comment by i2Echo** [comment]
## 路由
- home  / no auth
- games  /games no auth
- game  /games/:gameid no auth  comment 需要 auth
- user  /user/:uid/userhome no auth
- userset  /user/:uid/settings 等个人设置 auth
- login  /login no auth
- reg  /reg   no auth
- admin  /admin no auth
- adminmanage  /admin/usermanage or postmanage auth

**Comment by i2Echo** [comment]
## 游戏上传

### 上传方式
- 类似视频网站的方式
- 游戏分离出gameSource目录，用户只上传这个减少流量，核心js调用服务器上的，另外图片只上传新加的
- 上传时需要填写一个游戏信息表单，主要包括name,shortcut,author,maker,intro..., 需要登陆
### 游戏审核
- 暂时人工审核
- 以后考虑减少人工审核时间成本

### 发布
发布成功后会显示到games list以及个人post list，还会有一个game detail页面有关于游戏的详细信息以及玩家评论评分等

**Comment by zhaouv** [comment]
积分
难度->通关者1x,max保持者3x,原作3x
综合->原作
人气->原作0.8x,复刻者0.2x

**Comment by i2Echo** [comment]
## 主页细节
- logo
- 宣传图+简介+文档入口+游戏列表入口+项目入口
-  Features

**Comment by i2Echo** [comment]
## 游戏列表细节
* 自适应布局的卡片流
* 卡片内容：游戏封面图+头像作者+游戏简介超出省略+直接palybtn+详情morebtn

**Comment by i2Echo** [comment]
## 游戏详情细节
- 游戏卡片的内容+原作者+评分评分人数+游戏截图+简介完整版+评论人数评论

**Comment by i2Echo** [comment]
## 注册登录流程
### 注册
- 要素：Email+password+confirm pw（前端验证合法性，后端验证唯一性&正确性）
- 注册流程：输入Email和password正则验证合法性，MD5加密或其他加密，密文传输，后端验证Email未被注册后创建新用户分配唯一uid并发送激活邮件（三个要素>>code:激活码，Expiration:有效期，isActive:激活状态），激活后跳转userprofile设置昵称头像等个人信息，通过session保存用户登录信息或者token
### 登录
- 要素：Email/username+password(同样前端验证合法性，后端验证正确性)
- 流程：输入邮箱或用户名，输入密码（正确则跳转到前一页面没有则主页，错误提示密码错误重输），忘记密码，点击跳转到邮箱重置密码，输入邮箱验证后发送重置链接至邮箱，收件后点击跳转到重置页面重置。

**Comment by i2Echo** [comment]
## 评论区细节交互
### 评论输入区
#### 未登录
- 评论框以及提交按钮disable
- 提示登录后方可评论（可有一个链接或按钮方便快速跳转登录页面）
- avatar为未登录默认avatar
#### 已登录
- 显示当前用户头像
- 提示输入您的评论（暂时不限制字数）
- 未输入提交提示评论不能为空，
- 输入后点提交按钮提交评论，成功后显示到评论列表区（位置涉及评论排序，稍后再讨论）
### 评论显示区
#### 评论显示
- 以列表形式显示
- 复评以子列表形式
- 列表要素包括头像，用户名，评论内容，楼层，时间，回复按钮，其他action（删除，可能后面会加点赞或者分享），然后子评论列表类似结构
- 需要分页（分页细节待定）
- 懒加载（结合后端再考虑）
#### 复评（即回复已发的评论）
- 点击回复按钮即可在要回复的评论下方动态插入一个评论框（未登录不执行，只提示请先登录），操作类似于评论框
- 再次点击移除评论框
- 位置根据编号从新到旧（若增加点赞之类的还可以考虑热评靠前）
#### 删除评论
- 只对当前登录用户的评论显示该选项（管理员再说）
- 主评论删除后显示该评论已删除字样，其他信息包括字评论全部保留
- 复评删除后就直接删除（数据库后台可保留，给个状态表示已删除，前端根据状态决定显不显示）

**Comment by i2Echo** [comment]
### header部分细节交互（有响应式方案）
#### 要素
- logo+title
- 导航（home,games,about暂时就这三个）
- avatar（登陆后显示头像hover提示”点击选择个人设置“点击弹出个人信息相关设置列表（未确定细节）未登录显示默认avatar并hover提示点击登陆）
#### 自适应方案
- 小屏下header条只显示菜单按钮，logo+title
- 点击菜单图标按钮从左侧弹出一个列表层（类似于Android App的左侧菜单栏），从上至下依次为个人信息（头像，name，设置等，未登录显示默认avatar以及未登录字样），然后导航超链接列表并各带相应含义前置图标
- 显示状态随屏幕大小切换

**Comment by i2Echo** [comment]
### footer部分细节交互（有响应式方案）

#### 要素
- 超链列表
- copyright信息
#### 超链内容（待讨论）
- H5魔塔（docs, github, editor）
- 关于我们（aboutus, changelog）
- 联系我们 （feedback，qq群, email）
- 友链（。。。）
#### 响应式方案
- 超链部分：依内容分为四块，大屏以四块一行显示，小屏一块一行竖直显示，全部自适应宽度
- copyright单独一行居中，大屏小屏下只变化宽度

**Comment by ckcz123** [comment]
上传部分具体细节：

* 用户需上传整个包 （理由：有可能会对部分核心代码如core.js进行改变）
* 强制要求上传大小不超过8M（强制要求用户压缩过大的BGM）
* 上传时需填写一个表单，如“标题”、“版本”、“原作”、“简介”等等。
* 用户可以上传2-3个游戏截图；每个图片应不大于100KB
* 上传完毕后，将处于“未审核”状态，同时邮件提醒管理员审核。
* 管理员审核流程：
  * 下载上传的安装包，并检查data.js的name和表单中的name是否一致
  * 检查背景图（bg.png）是否被压缩过，如果很大可压缩为jpg格式，并在index.html中进行修正
  * 将sounds目录传到gitee上并开启bgmRemote，从而节省服务器本身的带宽
  * 进行JS代码压缩
  * （可选）开无敌模式来检查一遍游戏Bug
  * **管理员可直接编辑用户的表单信息，比如错误的name和其他不规范的表述等**
* 审核完毕后：
  * 将压缩包重新上传并替换原来的压缩包
  * 解压并发布到name那个目录下，生成游戏地址，并将“未审核”标记为“已通过，游戏地址xxxxxx”
  * 邮件通知上传者，“审核成功”，并在列表中显示
* 编辑和再发布
  * 用户可以随时编辑上传时的表单信息
  * **如果审核已经通过，则需提示用户：你的塔已经过管理员的二次处理后发布，如需进行编辑处理请直接在游戏内下载离线版本（进游戏 - 系统菜单 - 系统设置 - 下载离线版本）后再编辑，否则会被拒绝**，（防止管理员处理发布后用户编辑重新使得还需要管理员二次编辑）
