### ISSUE TITLE
关于额外素材tileset.png的想法与实现

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#224]
目前，H5魔塔样板最大的瓶颈仍在在于“素材的导入”。
具体而言，如果想增加大量自定义素材，需要通过便捷PS工具等导入到terrains.png，并且全部是单列，极度不友好。这也使得野外风制作变得相对困难，增加大量【素材处理】的工作量，甚至使人望而却步。
虽然贴图可以一定程度上缓解这个问题，但是仍然得承认，很不方便。
我们希望能像RM那样，直接导入一张野外风图片，就能直接任意绘图，而无需直接导入再注册。

为了解决这个问题，目前有一个想法就是，允许导入一张额外的`tileset.png`，其宽高可以是任意的32倍数（可以不允许宽度过宽）。
这个`tileset.png`无需注册，`(x,y)`的索引`index = 100*x+y`，数字为`number = 10000+index`，ID为`id = "X"+number`（T被地形的自动注册用了，因此可用X）。
无需注册，替换长宽后也能立刻使用，也不一定需要地图生成器来提供支持。

* [x] 运行时支持：根据数字>10000，或ID为`X10000`以上的，自动视为`tileset.png`的内容。
* [x] 地图编辑器editor的支持
* [ ] ~~地图生成器的支持（待定，也许不需要）~~

**Comment by ckcz123** [comment]
如果一个可行，之后再考虑推广到任意多个extra.png的情况。
即，在全塔属性中增加一个`extra_images`项，可以导入若干个大图直接使用。

**Comment by zhaouv** [comment]
指定起始索引, 然后读图片时通过\<img\>的属性获取宽高  
通过[起始索引, 起始索引+宽×高) 判定一个map的数字是否属于extra
