### ISSUE TITLE
编辑器重构

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#328]
https://github.com/zhaouv/mota-js/blob/refactoring-editor/_server/refactoring.md

**Comment by zhaouv** [comment]
# 重构

+ [ ] 按功能拆分文件
+ [ ] 左侧页面模块化, 方便添加
+ [ ] 不同的模式的文件操作尽可能模块化

---

文件结构
+ [x] editor_blockly 图块化事件编辑器, 基本不改动
+ [x] editor_multi 多行文本编辑器, 基本不改动
+ [ ] editor_table 处理表格的生成, 及其响应的事件, 从原editor\_mode中分离
+ [ ] editor_file 调用fs.js编辑文件, 把原editor\_file模块化
+ [ ] editor_game 处理来自core的数据, 导入为editor的数据, 从原editor中分离

+ [ ] 原editor_mode 移除

---

某些注意到的点

+ 地图的编辑与其他(如全塔属性和楼层属性), 现在的文件操作的模式是完全不同的  
  楼层文件的储存与其他不同

+ functions和plugins的借助JSON.stringify的replacer特殊处理

+ 目前editor.map中储存的是info\<object\>, 准备改为和core一致只储存数字

## 功能改进

+ [ ] 大地图  
  在切换时, 每次都回到最左上->每个楼层记录一个位置  
  四个箭头不能长按

## 左侧页面模式

标题? 保存按钮? 添加按钮? 删除按钮?

自定义内容?

表格?

**Comment by ckcz123** [comment]
blockly对于无法识别的图块原样返回

![image](https://user-images.githubusercontent.com/8597348/54731836-767f2880-4bcb-11e9-9730-b07648b473dc.png)

**Comment by dljgs1** [comment]
- 【全塔属性】、【楼层属性】等常用的编辑栏切换可以有快捷键，如F：楼层属性、E：事件编辑……或者可以自由建立快捷键到命令的注册表。

- 常用的地图编辑快捷键/命令：复制ctrl+c、粘贴ctrl+v、（复制可绑定为现在的“选中xx位置事件” 粘贴为复制xx事件到此处），撤回ctrl+z、取消撤回ctrl+y

- 一些可能的操作优化：双击图块后直接进入事件编辑；可以按住拖动图块与事件。

**Comment by zhaouv** [comment]
添加编辑表格按钮，直接用脚本编辑器来编辑表格对应的comment.js  
相应的,*comment.js的文件结构也要修改

**Comment by ckcz123** [comment]
- 修改系统的触发器（下拉菜单增加新项）
- 在编辑器修改`comment.js`：现场发readFile请求读文件，然后开脚本编辑器进行编辑

**Comment by zhaouv** [comment]
大地图添加滚动条

**Comment by ckcz123** [comment]
- 删除注册项
- 修改图块ID
- 怪物和道具也能像其他类型那样查看“图块信息”（而不只是具体的怪物属性）

**Comment by ckcz123** [comment]
- 事件编辑器和脚本编辑器可以只保存但不退出

**Comment by zhaouv** [comment]
> * 事件编辑器和脚本编辑器可以只保存但不退出

这样就看不到报错了

**Comment by ckcz123** [comment]
**素材区的重构**
现在素材区很恶心，主要表现在若怪物或道具太多，则需要向下滚动非常长，可以考虑进行重构，例如：

- items.png仍然保持一张图存在，仅存在内存中。
- 在素材区显示时，按照每50个进行拆分成`items1.png`, `items2.png`等等（类似`core.splitImage`），每50个新开一列
- 点击素材时根据其在第几个子素材和位置，来动态计算在原始素材上的素材索引，使用原始素材进行地图绘制。（这样运行时也不会冲突）
- 追加素材仍然只对原始的`items.png`进行追加。
- 主要是对怪物（enemys.png），道具（items.png）和NPC（npcs.png）进行这样的操作；不然太长了也确实难以寻找怪物。

**Comment by zhaouv** [comment]
`显示文章`解析回有标题和图像的空多的块

**Comment by ckcz123** [comment]
新增功能：地图选点
即，对于某些需要选择点的事件（显示、隐藏、开门、楼层切换……），提供一个按钮，点击弹出一个模态框，能在其中直接地图选点。
需要利用 `core.drawThumbnail` 在一个画布上绘制某层的缩略图。

![image](https://user-images.githubusercontent.com/8597348/56427189-89316e00-62ed-11e9-8438-781d9df8123e.png)

**Comment by ckcz123** [comment]
[新增门和对应的开门动画](https://h5mota.com/games/template/_docs/#/personalization?id=%E6%96%B0%E5%A2%9E%E9%97%A8%E5%92%8C%E5%AF%B9%E5%BA%94%E7%9A%84%E9%92%A5%E5%8C%99)不再需要开文件。
比如可以在哪加个【绑定开门动画】的按钮

**Comment by zhaouv** [comment]
? 编辑器使用可拖拽和调大小的窗口做容器  
搜到可做参考的项目如下  
http://demo.jb51.net/js/2015/js-win-drug-cha-close-demo/  
https://github.com/Lucent/drag-resize-dock  
https://github.com/michaeldewayneharris/Popit  
https://github.com/abidibo/moopopup

**Comment by ckcz123** [comment]
插件编写增加判定，如果保存时框内不是以 "function\s*\(\)" 开头（也就是用户直接写的脚本），则自动添加一个 function() { } 将代码包装起来。
主要作用在于，新增插件后框内是null，双击编辑时用户很有可能直接写脚本代码，而不是用function()包装

**Comment by ckcz123** [comment]
3.0中编辑器的重构：
- [ ] 按上述思路整体重构编辑器的结构
- [ ] 合并素材terrains的显示；素材折叠，选中后类似悬浮窗形式显示全部帧
- [ ] 取消注册机制，tips的修改等

**Comment by tocque** [comment]
# 3.0编辑器

总体思路  
+ 完全重新设计界面功能布置, 优化界面交互, 仿照vscode
+ 进一步分离界面和数据操作

## 结构

文件小写, 必要时用下划线分割, 类名使用驼峰

- [ ] editor_blockly.js 图块化事件编辑器
    - [ ] 增加dark主题
    - [ ] 默认不显示json, 通过按钮与blockly工作区相切换
- [ ] editor_multi.js 多行文本编辑器
    - [x] 更换为monaco
- [x] editor_list.js 即原先的 editor_table, 将元素更换为ul/li, 每个表格分配一个实例
- [ ] editor_table.js 生成表格样式的控件, 用于怪物和物品数据的编辑, 考虑引入第三方库
- [ ] editor_file.js 调用fs.js编辑文件
    - [ ] 将数据查询拆分
- [ ] editor_map.js 地图编辑的数据操作
- [ ] editor_game.js 处理游戏数据, 导入为editor的数据, 编辑数据, 从原editor和editor_file中抽离. **只有此文件允许`\s(main|core)`形式的调用**(以及其初始化`editor_game_wrapper(editor, main, core);`)
editor_util.js 处理颜色等函数
- [ ] editor_listen ? 考虑移除大部分事件监听, 拆分到各个界面文件中
    - [ ] contextMenu 右键菜单类, 通过传入配置生成
- [ ] editor 执行初始化流程加组合各组件
- [ ] 原editor_mode 移除
- [x] table\*comment.js 调整注释内容, 增加了短中文名

- [ ] editor_view.js 界面主体
    - [x] topBar 管理面板间切换
    - [x] infoBar 底部信息栏, 允许各模块在信息栏上显示信息
    - [ ] notify 管理右下弹框的类, 代替原先printe和部分alert
- [ ] view_mappanel.js 地图编辑
    - [x] mappanel 地图面板, 包含部分侧栏功能 ? 考虑拆分
    - [x] mapExplorer 地图列表, 引入Sortable.js 可以通过拖拽调整地图顺序
    - [ ] canvasManger 图层管理的类 ? 管理图层的显示,增删
    - [ ] tileEditor 图块编辑器
        - [ ] iconLib 素材区,  ? 图块编辑的从属
    - [ ] mapArrayEditor 地图数组编辑, 将原先新建地图时的数组编辑抽离至此 
    ? 考虑将贴图, 远景等图层也加入图层编辑中
- [ ] view_datapanel.js 数据界面, 包含了全塔属性, 怪物和物品的数据编辑
    [ ] 怪物和物品使用类似表格的方式编辑
- [ ] view_resourcepanel.js 资源管理界面, 包含图片素材导入和图块属性设置
- [ ] view_commoneventpanel.js 公共事件界面
- [ ] view_scriptpanel.js 脚本编写界面
- [ ] view_pluginpanel.js 插件管理界面
    - [x] 内置云端插件库

## 未明确的设计

+ 插件编写和脚本编辑面板是否使用多编辑器实例
    切换编辑项时如何保存
    性能问题
+ 地图列表是否使用树形控件
    加入树形控件有利于管理地图, 但是将失去调整地图顺序的功能, 从rm的先例来看, 树形控件不恰当使用可能导致地图混乱嵌套
+ 导入云端插件
    ? 目前插件库中插件冲突较多, 使用方法各异, 导入插件到本地功能是否需要
+ 素材导入
    ? 自动导入素材 目前h5很多工程里有冗余素材, 可能导致加载项体积增大(是否需要确认素材的界面)
+ 运行时
    是否需要使用游戏运行时
+ 输出release
    @fux4 的提议, 编辑器输出配置好的release版本游戏
    ? 编辑器调用压缩js工具
    需要额外输出检查? 部分配置从project/data.js main.js移动到编辑器中?
+ 部分编辑界面的布置及细节
    地图数组编辑和其它非tile编辑下 工作区显得过于空旷?
    怪物/物品编辑用表格是否恰当
    侧栏是否可调整宽度
    统一配色 ? 编辑器皮肤 是否需要抽离可管理的配色系统
    个性化设置在本地不同编辑器文件是否/如何统一 ?
+ 其他预留接口安排
    ? 登录系统, 云造塔

## 遇到的困难

启动服务不支持svg格式文件

**Comment by zhaouv** [comment]
在表格(列表生成时)加入更多元信息, 使得_file/_game处理时不再需要根绝类别来进入不同的分支处理

**Comment by tocque** [comment]
fileData 数据, 由文件读取的数据和 comment 结合, 内部用field字符串标记路径
+ stringify() 由数据对象生成字符串 
+ save() 保存文件
+ createSubFile() 用子树生成一个新文件
    node 节点

panel 面板 { map, data, resource, commonEvent, script, plugin }
+ active()/unactive() 激活

    editor 编辑器, 一个独立的工作区域, 包含零个或多个控制器 {
        editor_list, editor_table, 
        map: mapExplorer, eventSearch, canvasManager, tileEditor
        data: null
        resource: 
        commonEvent: blockly
        script: mutli
        plugin: pluginLib, pluginView
    }
    + active()/unactive() 激活
    + undo()/redo() 撤销/重做
    + regShortcut() 注册快捷键
    + regContextMenu() 注册右键菜单
        control 控件, 每个控件与一个 node 绑定 {
            mapArray: tileControl
            Array, Object: list.tagList table.tagList
            text: list.text, table.text
            options: list.select, table.select
            bool: list.checkbox, table.checkbox
            script: list.textModel, table.textModel
            event:
        }
        + undo()/redo() 撤销/重做的内部实现

materialSelector

// 组件
layer 弹框, 弹出时会屏蔽其他区域的点击和按键 {
    uipreviewer, flagManager, textEditor, scriptEditor
}
+ open()/hide()

notify 右下气泡
+ pop()/close() 弹出/关闭

infoBar 信息栏, 左侧为系统级的提示, 右侧为各面板/控制器的信息
+ tip() 显示提示
+ setWarn() 设置警告
+ applyInfoBlock() 在右侧申请一个信息块
    infoBlock 信息栏上的块
    + update() 

button 按钮 { infoBlock }
+ update() 传入的参数将调用content生成HTML
+ disable() 使按钮失效

contextMenu 右键菜单
+ open()/close()

navBar 导航栏 { sideBar }
+ bind()

scrollbar 滚动条

//////
inputManager 全局性的输入管理器
+ stop()
