### ISSUE TITLE
可视化编写ui

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#329]
涉及的内容:

画标题

各颜色和大小的文字

图标

静态(物品等)/动态(怪物和npc)

api, 游戏数据如何放进去

两个可能的方案

+ 图块式编辑  
  很容的使用游戏数据  
  js代码直译式的转成图块  
  显示一个粗糙的实时预览  
  ![image](https://user-images.githubusercontent.com/26158289/54843746-879f6680-4cab-11e9-9315-3782a119b96b.png)

+ 画板式的编辑  
  类似C#/VB式的拖拽画图来制作ui  
  直观

**Comment by ckcz123** [comment]
Done. #375 
已支持静态预览；实时预览尚待研究
