### ISSUE TITLE
怪物描述

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#332]
每个怪物可以填描述  
显示在手册详细信息的特殊属性上面（也可能要重新布局页面）  
可以给魔王章鱼魔龙加一段话描述背景，来增加作为rpg的代入感  
蓝海向的功能提议

**Comment by ckcz123** [comment]
在V2.6中，可以重写`_drawBook_drawName`等函数来自定义绘制怪物手册。
此项不应作为样板本身的内容。
