### ISSUE TITLE
global:xxx -> core.getLocalStorage("xxx", 0)/core.setLocalStorage("xxx", ...)

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#362]
功能提议  
把localstorage映射到global:xxx的形式, 方便事件流制作成就以及其他功能, 例如教程性质的对话全塔只在第一次显示

**Comment by zhaouv** [comment]
global可能会破坏录像

提供一个不计入录像的方块,类似if块,其内部的块全部跳过录像?

**Comment by zhaouv** [comment]
无法解决 成就改变了游戏数值  

提供两个块 全局->flag  flag->全局  
只有这两个允许操作global  
global不能直接嵌入

**Comment by zhaouv** [comment]
『设置全局存储』在游戏时设置全局量并把其入录像, 在播录像时不设置全局量，『获得全局存储』在录像时从录像读值

**Comment by zhaouv** [comment]
无需提供专门的块, calValue函数中加判定

**Comment by ckcz123** [comment]
Fixed.
