### ISSUE TITLE
有关录像和回放问题的探讨

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#37]
目前的想法：记录“所有有效操作”；并且希望能尽量压缩以节省存储空间。
在存档时也存储操作列表，读档时也将其读取。

有效操作主要包含如下几类：
* 勇士移动，记录方式 `UDLR`，后面可以接数字代表多少次操作。如 `U4L2D3` 代表上四格左两格下三格。
* 使用道具，记录方式 `Ixxx#`，中间的`xxx`为道具ID。如 `Ipickaxe#` 代表使用破墙镐。
  * 如需进一步压缩，`xxx`还能简写为道具的index（当前拥有的第几个道具）。
* 使用楼传器飞到某一层，记录方式 `Fxxx#`，中间的`xxx`为目标楼层的floorId。如`FMT0#`代表飞往MT0层。
  * 如需进一步压缩，`xxx`还可存放楼层的`index`（在`main.js`中的`this.floorIds`顺序定义）。
* 触发自定义事件的选择，记录方式 `Cx`，中间的`x`为第几个选项。如`C2`代表当前选择第二项。
* 使用商店/快捷商店，记录方式 `Sxxx#y1y2y3...`，中间的`xxx`代表快捷商店ID，`y1y2y3`等代表该商店的选择项。如 `Sshop1#0011` 代表此时在商店`shop1`购买了两次攻击和两次防御再离开（假设0号选项为攻击，1号选项为防御）。
  * 如需进一步压缩，`xxx`还能简写为商店的`index`（在`data.js`中的`shops`按顺序定义）。

**Comment by zhaouv** [comment]
建议生成一个固定的数组,内容是['up',down','left','right','item#Ipickaxe',...'shop1#0','shop1#2',...],然后记录中存下标

这样能类似base64那样压缩

**Comment by ckcz123** [comment]
> @zhaouv 
这种方式是不错，但是感觉你必须在存储列表以`,`分隔（不然12存在多种识别方式）；并且有关楼传器、自定义选项、商店使用等，总感觉不太好。

**Comment by ckcz123** [comment]
我不太喜欢用数组，还是觉得直接存字符串，往后直接append，也不用base64压缩。。。
至少不够直观（不方便调试）。。
1F的方法存在什么方面的问题呢

**Comment by ckcz123** [comment]
1F方法的改进：

**Comment by i2Echo** [comment]
我也赞成直接用短号字符串表示，就是压缩方法还不够彻底，比如即使U2D4L3U5（可省略表示一步）这样压缩但是UDLR还是出现频率最高，而且仅有这4个出现的频率高，所以压缩率不高；可以用哈弗曼编码的压缩方式（哈夫曼树），进一步压缩成二进制（关于可读性，反正是要编码解码的）这样上面原本是8个字节，进一步编码成2个字节,，1/4啊。。。应该可以了

**Comment by ckcz123** [comment]
目前已经决定分为两个部分：**内存的存放**，**编解码**

内存的存放(`core.state.route`)可以是一个数组，每一项是一个操作。
``` js
[
"up", "left", "right", "down", // 方向
"item:pickaxe", "item:xxx", // 使用道具
"fly:MT0", "fly:MT1", // 使用楼传器
"choices:0", "choices:1", // 选择某个选项
"shop:shop1:0011", // 在某个商店进行若干次操作
]
```

**Comment by ckcz123** [comment]
有关回放的想法：

目前我的想法是，主要执行如下操作：
``` js
core.prototype.replay = function() {
    // 如果已经播放完毕，则返回正常游戏模式
    if (toReplay.length==[]) {
         isReplaying = false;
         return;
    }
    // 取出下一项
    var action = toReplay.shift();

   // 执行操作，操作执行完毕的callback仍为本函数
   if (action == 'up') core.moveHero('up', function() {core.replay()});
}
```

然后如果中间触发了事件且需要操作，则仍从toReplay中弹出并读取。
