### ISSUE TITLE
录像存档相关（美化与加强）

### ISSUE THREAD

**Issue by ThinerDAS** [ckcz123/mota-js#384]
为了区分路线与存档的概念，称去掉路线与其他与游戏行为无关的数据（如存档时间）的存档为“裸存档”。

现提出以下加强方案：
1、加入一个游戏flag，允许录像存档的路线被优化：绝大多数有意义的红海塔的nop行走对程序无影响。无意义的走动与撞墙会被从路径中剔除裁弯取直，类似于瞬移的操作。无意义性的自动判定：如果一个时间轴上有两点的裸存档完全相同，则这两点间都是废操作。这一个判据可以将中毒等特殊情形与一般情形区分开来。
我们认为，游戏的行为与存档时间与存档时机无关。
2、录像存档加入时间轴，允许玩家拖动时间轴来浏览存档的内容——实现上可以在时间轴的每一点处记录一个裸存档，在时间轴上拖动时会读取上面的裸存档。
3、为了提高录像存档的可阅读性，在游戏中加入一个操作：做笔记。为了简化实现，笔记在创造以后只读。做笔记时，玩家可以输入长度最大为1000的静态字符串/md。做笔记的操作加入录像存档。这相当于录像存档的注释或解说。
补充：3与2结合就是：“运行到某行笔记”
这个的应用场景就是“快进到击败1区boss”

**Comment by ckcz123** [comment]
1. 裸存档是包含当前游戏时间、步数等信息的；就算不考虑这些，最大的问题在于存档操作是非常耗时的（稍微大一点的塔可能要~100ms）；因此使用存档来一步一判定属于不合理的行为，正确做法应是每一步后看有没有造成实质性的游戏状态变化。理论上可行，但是实际做起来不是非常容易，如果你有兴趣可以进行尝试。

2. 同1，核心问题在于【存档】这个操作是非常耗时的（稍微大一点的塔可能~100ms）；而且存档是很占用内存空间的；时间轴的每一步都有一个存档听起来很美好，然而受到很严重的时间和空间限制。

3. 看起来不是特别有必要，如果有兴趣可以自行实现对应的插件。

**Comment by ThinerDAS** [comment]
1. 考虑在所有的对游戏状态产生实质性变化的操作上加入hook。
2. 时间轴只有在播放存档的时候出现，所以考虑的因素只有内存占用；时间轴上出现的点的集合与正常游戏的自动存档时机保持一样即可。（貌似现在播放存档的实现是隔50步一存档）目前的实现貌似已经把这些存档放到内存里了，所以可能需要的只是时间轴的GUI。
3. 这个需求可以演变成在魔塔上运行的较高级的DSL，而现在的路线文件是其生成的机器码。笔记等价于调试符号或者调试输出。
