### ISSUE TITLE
官方的headless魔塔API

### ISSUE THREAD

**Issue by ThinerDAS** [ckcz123/mota-js#385]
最重要的底层接口：路线翻译成存档的api（尽可能快）；其他接口可以由其他魔塔研究者开发。

目前我作为非开发者实现headless手段粗劣肮脏，希望官方提供较规范headless接口。

**Comment by ckcz123** [comment]
从录像到存档目前唯一的方法就是从头播放录像，没有其他的方式。
存档记录了勇士的各种状态和当前的地图数据等，这些强依赖于游戏的进行过程，即没办法脱离【运行】这一过程而直接得到最终状态。
如果你有更好的方式，欢迎提出并发PR。

**Comment by ThinerDAS** [comment]
我了解的方式不多。

我目前的实现是将魔塔里的和window与素材加载相关的所有代码删除，然后直接调用js函数实现，修改量巨大，目前仅能跑通银河前20层的情形。
我咨询了身边的一个web方面了解比较多的朋友，对这个应用场景他给的建议是headless chrome。

真正的headless除了保底的路线存档翻译以外，还有很多的挑战。举例来说，当前h5mota架构下，获取每一种血瓶增加血量不好做。所以更结构化的数据对headless有好处。

**Comment by ckcz123** [comment]
Done.
