### ISSUE TITLE
spirte化与对应的素材管理

### ISSUE THREAD

**Issue by dljgs1** [ckcz123/mota-js#397]
# sprite化的event层
2.x对48高度的事件实现很麻烦，而且不能支持宽度超过32的角色。3.x 将把event层、event2层与hero层合并用sprite实现，bg和fg暂时不变。

## 1. sprite对象
sprite对象类（spriteObj）包含贴图的所有实际绘制数据（原图索引、位置、尺寸、帧行状态），其本身没有任何方法。

生存周期：
每个sprite通常与一个实际需要绘制的实体绑定，比如block，当block创建时同时创建一个的sprite，但block被删除后，sprite不一定被删除。如果被添加到spriteRender的对象列表中且没有被清除，则会驻留，因此需要手动删除在在spriteRender对象列表中的sprite对象。

动画：
通过对sprite对象的帧和行修改达到帧动画的效果，比如core.status.globalAnimateObjs的定时刷新。

## 2. sprite渲染
sprite渲染类（spriteRender）包含一个sprite对象列表、一个离屏canvas（用作缓存），可以绑定一个渲染目标destCtx。

### 定时刷新
spriteRender需要定期刷新（update），并通过自己的一个bool状态变量（dirty）判断是否需要重绘。如下动作均会导致dirty=true：
 - 添加新的对象：比如setBlcok后绘制一个block到当前地图，需要将其sprite添加到对象列表
 - 删除一个对象：比如击败敌人后，敌人消失，需要从对象列表中删除
 - 对象更新：比如一个animate的帧改变，或是勇士的坐标变化。

### 有序绘制
在添加、删除、更新对象时，需要保证绘制序列在优先级上有序。目前的优先级计算方法（从小到大排序）：
(obj.y+obj.height)*1000+obj.width
即优先绘制 y 坐标小的对象，在y等同时，优先绘制宽度小的。
（*先绘制的可能会被后绘制的挡住）

### block与sprite绑定
在block初始化时，根据其索引的sprite的id（目前直接用的event.id，容易与block本身的id混淆，需要修改）创建一个sprite对象。
在drawBlock时，不再直接提供canvas绘制，提供一个render对象。如果该block的sprite已经处于该对象，则直接更新sprite状态，无需实际渲染，否则添加到该render对象。
hero与block同理。

# 素材管理 

## 1. 素材导入
素材加载到工程中，一方面需要写入素材的数据信息（尺寸、定位、帧动画等），一方面需要添加素材贴图本身。

### 导入流程

支持任意尺寸的帧序列素材，导入时需要指定以下属性：
 - 原图（image或者是一个裁剪后的canvas），
 - 尺寸（一帧的长宽）
 - 帧数（一行有多少张帧图，默认一帧）
 - 行数（同一个素材的多个状态，比如行走图的上下左右，默认一行）

为了兼容原来的常用素材以及减少浪费，保留了几种固定尺寸的类型（oldTypes）。
 - terrains （32x32 1帧）
 - animates （32x32 4帧）
 - npc （32x32 2帧）
 - npc48 （32x48 4帧）
 - autotile （96x128 1帧或4帧）
如果导入的素材是oldTypes，添加到对应类型的图片中（如一个32x32的新素材会被添加到terrains.png最后一行）；否则，会被添加到sprite.png中（具体算法待定，目前暂用的是简单的堆叠）。

### 自动注册
如果导入的素材是属于特定类型（oldTypes），那么将免去属性指定，会将图像自动导入到对应的贴图并注册信息。
- [ ]  自动注册

## 2. 素材与元件
所有导入后的素材，会分配一个唯一的ID，在project/sprite.js 中记录了ID与素材属性与所在位置的表。这个ID代表的是素材，而非某特定**元件**。下以创建一个新敌人为例说明素材与元件的关系。

### 创建一个新敌人的流程

1. 建立一个新敌人项，这个敌人会分配一个enemyId，会注册到ememys.js中。此时的敌人是一个没有贴图的敌人。
2. 指定该敌人的贴图。（即，enemyId映射一个素材的ID）
3. 写敌人的数据。
4. （更新维护）修改敌人贴图、修改敌人数据

### 批量注册与绑定
要优化创建流程，需要尽可能减少1、2步的开销，并且同时使1、2步对3、4无影响。
当前样板的实现方法是素材与实体绑定，这会对步骤4有一定影响，并且锁死了1、2，导致修改删除素材项十分不方便，看上去在注册时速度极快，但可能会导致后续的维护效率降低。
因此，可以用将素材实体项快速添加的方法，将指定素材批量指定到敌人列表，将自动完成新敌人的创建并将该贴图指定到该项，降低1、2步的开销，同时保证3、4。

具体按如下步骤进行效率极高的批量注册与管理：
1.  素材导入（可以通过批量添加、自动注册完成，与原来的【追加素材】操作类似）
2.  **将素材从素材区拖拽到元件区**，完成元件创建。（比如，一个素材列表，代表当前导入的所有素材，一个敌人项列表，代表当前的敌人，将素材选中或者批量选中，拖拽到敌人列表的空白区域，或者点击注册，就可创建等量的敌人元件，并且自动绑定素材贴图）
3. 填写数据
4. 后续维护（这些贴图随时可以更换）

### 编辑器的建议

下面是一些可能的关于编辑器的建议。
- [ ] 右侧的素材区变成元件区，同样用贴图的方式显示，但可以支持增删，提供一个下拉列表可以切换（敌人/物品/地图图块）（数据区也许可以用canvas实现？）
- [ ] 素材区在左侧或者用一个弹窗显示，其中显示素材列表，可以用勾选的方式选中，然后批量添加到当前数据区（也可以用拖拽实现，但勾选应该更简单）
- [ ] 素材批量导入，确定一个类型或一个尺寸，然后可以在文件选择中一次性选中多个图片，点击确定后分析出图片中符合类型的素材进行批量注册，不符合的列出来单独处理（分析和注册这块的接口已经要做好了，主要是提供一个批量选择和实时刷新数据、素材区的功能）

**Comment by zhaouv** [comment]
### 编辑器

由于批量导入以及sprite添加的不可逆,需要以下两个功能
+ sprite: 删除没用过的+重排
+ 固定尺寸图片: 删除没用过的
 
元件区会和现有素材区类似  
素材区和追加素材要进行较大调整

**Comment by dljgs1** [comment]
几个API：
1. 注册素材：
core.sprite._registerSprite
// 参数：image, name, x, y, w, h, frame, line |  素材图片、名称（id），裁剪坐标，单帧宽长，帧数、行数，将其注册到数据库中

2. 删除素材：
core.sprite._unregisterSprite
// 参数：name, arrangeDirectly | 名称（id）、是否立即重排
如果是固定尺寸图片，立即重排（计算量较小可以立即完成）；如果是sprite，根据arrangeDirectly 决定是否立刻重排（如果图片多计算量可能会比较大，具体开销需要进一步测算）

3. 重排
core.sprite._rearrangementOldtype ： 重排固定尺寸的素材图
core.sprite._rearrangementSprite ： 重排sprite素材图

以上操作均会修改图片数据（project/images）与对应的sprite数据（project/sprite.js)，需要服务器回写文件。

**Comment by dljgs1** [comment]
编辑器目前主要需要完成的目标：

- [ ] 素材注册。目前新添加的素材，运行时可以通过api core.sprite._registerSprite 将素材合并到相应图片，并将信息注册到sprite对象(core.sprite.sprite)，需要将这个对象回写到project/sprite.js，对应的图片也要写回。删除时一样。

- [ ] 提供元件选择素材的方法。每个元件（包括items、enemy）多一个属性sprite用于选择贴图。每个元件的贴图不一定来自同一张图，所以展示的元件需要根据sprite拼凑(绘制单张sprite的方法为 ： core.sprite.drawSpriteToCanvas(name, ctx, bias)，依据sprite的name将贴图绘制到ctx上，偏移值为bias（例{x:10,y:10,width:32,height:32}}。

**Comment by zhaouv** [comment]
+ [ ] 在单文件导入素材完成的基础上, 每次打开编辑器fs.readdir扫描project/images/\<item\>等文件夹, 将每个xxx.png且没有对应的xxx.mark的图片按照默认设置导入为对应素材, 并添加xxx.mark  
想修改时删除xxx.mark并替换xxx.png

**Comment by tocque** [comment]
自动注册 + 选择性打包
考虑对于rmxp格式的素材直接适配, 将其放入project/images的对应文件夹即可使用
放弃素材拼接, 直接将资源打包, 请求整个压缩包后在本地解压
+ 可能会有人放入大量无用素材, 因此需要记录素材实际使用情况
    + 具体方法: 对于地图素材可以扫描地图? 对winskin和picture等则需要扫描事件, 除此之外还需要可编辑的列表用于处理其他情况(如脚本中使用素材或转变图块)
+ 解压过程是否会成为瓶颈?
+ 具体分类? 目前考虑为oldtype / npc / enemy / item / animate / custom / autotile / tileset 其中custom存储自定义素材, 以及picture / winskin / fog 三种其他素材

**Comment by zhaouv** [comment]
> 自动注册 + 选择性打包
> 考虑对于rmxp格式的素材直接适配, 将其放入project/images的对应文件夹即可使用

之前issue事实上包含了此功能

> 放弃素材拼接, 直接将资源打包, 请求整个压缩包后在本地解压

除了节省一些空间和拼起来无本质区别, 缺点是无法用url使用, 节省的空间要考察

> 
> * 可能会有人放入大量无用素材, 因此需要记录素材实际使用情况

没有被元件使用的素材会自动删除, 提醒作者发布前删除所有未使用的元件更合理, 之后用约定过的删除未使用素材的功能, 脚本可以以字符串拼接的形式最终使用元件, 扫描原理上有漏洞

>   
>   * 具体方法: 对于地图素材可以扫描地图? 对winskin和picture等则需要扫描事件, 除此之外还需要可编辑的列表用于处理其他情况(如脚本中使用素材或转变图块)
> * 解压过程是否会成为瓶颈?
> * 具体分类? 目前考虑为oldtype / npc / enemy / item / animate / custom / autotile / tileset 其中custom存储自定义素材, 以及picture / winskin / fog 三种其他素材
