### ISSUE TITLE
3.0样板对蓝海塔功能的支持

### ISSUE THREAD

**Issue by dljgs1** [ckcz123/mota-js#399]
【例1】
区域楼层管理。
- 功能内容：
对地图添加区域属性，对地图进行分区域的管理。体现在如下几个方面：
a. 编辑器，在选择某区域后，显示当前区域的楼层列表。
b. 数据统计，统计当前区域的怪物、宝物数目。
c. 存档优化。在开启存档优化后，只有当前区域会进入存档，其他区域不会进存档。
 - 实现建议：在楼层属性中增加area字段，对地图按area进行区分。
 - 应用场景：多区域大型蓝海塔。

欢迎补充，格式如下：
002. 名称：……
功能内容：……
实现建议（选填）：……
应用场景：

**Comment by ThinerDAS** [comment]
名称：边测边改
功能内容：可以在拆塔界面调整魔塔地图与怪物属性；调整完可以实时重放录像
实现建议：设计可变图块，每个可变图块对应一个可以在造塔界面设置的图块范围，调试模式游戏界面里右键点击这个图块可以将它的内容换成另一个；右键怪物还可以调节怪物能力；在调试结束的时候可以导出可变图块的赋值map，发布时将可变图块的赋值map赋给变量，固定即可。
应用场景：艾转换

**Comment by zhaouv** [comment]
> 名称：边测边改
> 功能内容：可以在拆塔界面调整魔塔地图与怪物属性；调整完可以实时重放录像
> 实现建议：设计可变图块，每个可变图块对应一个可以在造塔界面设置的图块范围，调试模式游戏界面里右键点击这个图块可以将它的内容换成另一个；右键怪物还可以调节怪物能力；在调试结束的时候可以导出可变图块的赋值map，发布时将可变图块的赋值map赋给变量，固定即可。
> 应用场景：艾转换

通过道具很容易实现，使用道具后点击屏幕的一个点，然后把所有地图的该块转变图块就行。改怪物属性做成另一个的类似的道具即可。而且可以做成一段脚本粘控制台对已有的塔使用

**Comment by ThinerDAS** [comment]
> > 名称：边测边改
> > 功能内容：可以在拆塔界面调整魔塔地图与怪物属性；调整完可以实时重放录像
> > 实现建议：设计可变图块，每个可变图块对应一个可以在造塔界面设置的图块范围，调试模式游戏界面里右键点击这个图块可以将它的内容换成另一个；右键怪物还可以调节怪物能力；在调试结束的时候可以导出可变图块的赋值map，发布时将可变图块的赋值map赋给变量，固定即可。
> > 应用场景：艾转换
> 
> 通过道具很容易实现，使用道具后点击屏幕的一个点，然后把所有地图的该块转变图块就行。改怪物属性做成另一个的类似的道具即可。而且可以做成一段脚本粘控制台对已有的塔使用

每个块都是分开修改的；使用道具太麻烦了，除非能绑在数字键上，并且还要选择目标图块；如何管理可变图块的赋值？

**Comment by zhaouv** [comment]
无法区分点击是移动还做操作，所以你提到了调试模式。进入调试模式本身是需要一步操作的，可以理解成点击道具。选择目标图块也是必然的，否则无法区分多种可变图块，就是你说法中的右键单击一个图块。    
点击后弹框，初始是当前的图块数字+1，直接点确定就行，还嫌麻烦的话就再做一个直接用+1的道具。    
修改数据的道具就是弹一个json化后的字符串textarea。  
再有一个道具用来输出修改后的结果。这步在你的源描述是一样的，因为游戏运行时不加载fs.js

**Comment by ThinerDAS** [comment]
> 无法区分点击是移动还做操作，所以你提到了调试模式。进入调试模式本身是需要一步操作的，可以理解成点击道具。选择目标图块也是必然的，否则无法区分多种可变图块，就是你说法中的右键单击一个图块。
> 点击后弹框，初始是当前的图块数字+1，直接点确定就行，还嫌麻烦的话就再做一个直接用+1的道具。
> 修改数据的道具就是弹一个json化后的字符串textarea。
> 再有一个道具用来输出修改后的结果。这步在你的源描述是一样的，因为游戏运行时不加载fs.js

感觉你的设计没有太大问题，先做出来再细化需求吧，先解决有无问题。

**Comment by ThinerDAS** [comment]
名称：闪耀的动作
功能内容：开启绚烂开关以后魔塔操作做得绚烂，参考3A大作，以下是例子：破墙打怪加上粉碎粒子效果，炸弹加上粒子效果和震撼效果（屏幕抖动、音效），飞时勇者移动到对应位置，拿宝物的时候声音清脆、宝物的图像从图块移动并缩小到屏幕左方能力值对应图标，移动到图标以后勇者对应图标像心跳一样渐变增大10%增大亮度50%持续0.2秒以后恢复原状。
实现建议：webgl？
应用场景：美丽的魔塔

**Comment by ThinerDAS** [comment]
名称：巡逻怪
功能内容：对于一个怪物，可以对其指定一条巡逻路径，怪物沿着这条路径巡逻。巡逻路径是一个while1播放的动作序列，包括上下左右行走和停止。勇者走一步怪物走一步；也可以指定一个开关，在这个开关开启的时候怪物开始巡逻。
怪物巡逻时碰到其他怪物有四大种冲突处理策略：可以暂停巡逻（阻塞）、穿透怪物、反弹（反向巡逻路径）、与阻挡怪物战斗（巡逻怪先攻；可选实现，可以留个接口）；怪物巡逻碰到勇者发生战斗，怪物先攻，勇者碰怪物则勇者先攻。
在非穿透的冲突处理策略下，怪物排队巡逻的时候，容易发生一个格子前脚怪物刚走，后脚下一个怪物走到这个格子的情况，或者需要指定怪物优先级以确定阻塞关系；或者采用复杂的算法确定是否会发生碰撞。
实现建议：地图里的事件属性？
应用场景：巡逻塔——确定性的动作魔塔

**Comment by ThinerDAS** [comment]
名称：磁铁
功能内容：模拟点击宝物，自动吃宝物；可以在菜单页面里选择磁铁策略，如不自动吃红宝石、蓝宝石而自动吃黄钥匙等
实现建议：图论搜索，模拟点击，不需要单独实现一个动作
应用场景：宝物多的所有塔

**Comment by ThinerDAS** [comment]
名称：路线的调试模式
功能内容：在屏幕某处即时显示伤害和、宝物和、剩余金币和、商店各个选项已加次数、仇恨值等内部变量
实现建议：集思广益？
应用场景：对求和、内部变量有需求的所有塔

**Comment by zhaouv** [comment]
转群友“量子杰克”的提议  
功能名称：一键绑机关门  
功能内容：地图选点，选一个门和几个守卫，就自动绑好机关门事件。   
实现建议：显示在样板界面上，如果已有战后事件则放在后面。   
应用场景：存在大量机关门的塔。

**Comment by tocque** [comment]
名称：编辑器左侧面板优化
功能内容：将左侧面板紧凑化，便于魔塔制作
实现建议（选填）：各修改项只保留中文名称和属性，将条目名称和注释放入名称title属性中或弹框提示(针对手机)
去除表格框线
数值类型用input代替textarea，事件等复杂代码类型尽量使用专门界面进行编辑，在面板上只保留进入专门界面的入口，项目组提供折叠功能
应用场景：所有塔(的编辑器)

**Comment by tocque** [comment]
名称：编辑器面板优化
功能内容：将部分功能放入单独页面中
实现建议（选填）：全塔属性，脚本编辑，插件编写，追加素材，公共事件这些功能与地图没有关系，考虑从地图下方的select中移除，并设置专门的面板，以更好的组织功能
其中涉及脚本/事件的几项可做成类似插件库那样，右边为编辑区左边选择项目
在上方增设一栏按钮用以在地图及上面几项间切换
应用场景：所有塔(的编辑器)

**Comment by tocque** [comment]
名称：无限图层显示
功能内容：允许玩家自行添加新图层，设定与其他图层（包括系统提供图层）的相对关系，且图层支持跟随玩家移动，自动卷动，可以用tilemap，图片，或者脚本生成内容作为图层内容
实现建议（选填）：在编辑器上适配相应的编辑功能
应用场景：画面效果较为复杂的塔

**Comment by tocque** [comment]
名称：事件编辑器优化
功能内容：固定每个事件的事件入口，并且根据事件入口提供对应可用的事件块
将右侧代码区隐藏，通过按钮切换
禁止横向滚动blockly工作区
实现建议（选填）：改写函数，禁止删除事件入口，彻底移除事件入口分类
移除toolbox中事件入口类
应用场景：造塔时

**Comment by tocque** [comment]
名称：素材管理优化
功能内容：在编辑器中新增素材管理界面，提供对应素材文件夹下的文件列表，可以通过直接勾选的方式进行素材注册(面向BGM，SE及animate)以及素材失效检查
应用场景：大部分塔

**Comment by tocque** [comment]
名称：大地图完整显示
功能内容：在编辑器中大地图完整显示，通过滚动条进行进一步移动，考虑增加修改功能，便于修改
实现建议：需要进一步提高viewport方面接口的自由度
应用场景：大部分塔

**Comment by ThinerDAS** [comment]
名称：自动使用咸鱼杖
功能内容：在战斗或者走领域的时候如果会死那就根据将要减的血，自动提前使用咸鱼杖
实现建议：战斗前或者经过领域前while(血不够){使用咸鱼杖;}
应用场景：带纯血咸鱼杖的所有塔

**Comment by voderl** [comment]
名称：地图尺寸切换
功能内容：比如有些楼层13×13，有些楼层15×15  有些楼层 11×11
实现建议：不需要再在周围强行用墙描边而从根本上实现尺寸的更改，更亲民友好！
应用场景：好做就弄，不好弄就咕。

**Comment by ThinerDAS** [comment]
名称：旋转地图
功能内容：游玩时可以旋转或者翻转地图，旋转和翻转只是视角效果，对实际没有影响
实现建议：画地图的时候加一个0-7的参数，翻转参数存在游戏的localforage里
应用场景：有切换视角需要的魔塔

**Comment by user670** [comment]
名称：不退出游戏上传成绩
功能内容：上传成绩但不退出到标题画面。（注意录像验证的问题）
应用场景：有多个分区，希望每个分区都记录成绩的塔（参见云造塔接力赛）；小游戏

**Comment by tocque** [comment]
名称: 自由调整可见区域大小
功能内容: 如题
应用场景: 编辑器大地图编辑, 5*5, 8*8等非标准尺寸地图(如国际象棋魔塔)
实现建议: resizeViewPort(x, y)
