### ISSUE TITLE
多事件页 & 自动事件

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#401]
支持多事件页和自动执行。该自动事件能绑定到具体的点，当条件满足时自动执行。

具体设计如下：
 - 在当前地图选点在现有六大类型上增加一个新类型：auto（或者autoEvent）
 - 该类型支持多个事件，每个分别针对于事件页
   - 由于多事件页可能会较多，推荐将每个事件页独立开，即每个自动事件一个框
   - 即类似于如下内容：
    ``` js
    "autoEvent1": {
        "1,2": {...},
        "1,3": {...}
    }, 
    "autoEvent2": {
        "1,2": {...}
    }
    ```
 - 在游戏初始化时，扫描全部楼层的`autoEventX`，然后加入数组；
   - 自动事件仅在`updateStatusBar`时检测，并对应插入执行
 - 每个自动事件应存在如下选项：
   - 条件，仅当满足时才会触发
   - 是否仅在本层检测
   - 优先级：默认为0，相同条件同时检测满足时高的比低的先执行
   - 延迟执行：如果此项为true，则在当前事件流执行完毕时才执行
   - 是否只执行一次即销毁（不再检测）；虽然我觉得这个可以由用户自己用独立开关控制
 - 允许直接强行通过【插入自动事件】直接执行一个自动事件的内容（和插入公共事件类似）。
 - 避免多次执行问题
   - 在执行前设置该自动事件已经被插入；事件执行后设置该自动事件已经被执行完毕
 - 坐标点/当前楼层的改变问题
   - 现在当前坐标点由`core.status.event.data.x`和`core.status.event.data.y`确定，当前楼层由`core.status.floorId`决定
   - 推荐把当前楼层改成`core.status.event.data.floorId`
    ``` js
    var floorId = data.floorId || core.status.event.data.floorId || core.status.floorId;
    ```
   - 当插入自动事件时，将当前坐标和楼层进栈，然后自动事件执行完毕时出栈
    ``` js
    core.setAutoExecuting(event.index, true);
    // 如果该事件只执行一次，则进行销毁
    core.insertAction([
        {"type": "function", "function": "function() { core.pushLoc(); }"},
        // 用do-while(0)包一层防止break影响事件流
        {"type": "dowhile", "condition": "false", "data": event.list},
        {"type": "function", "function": "function() { core.popLoc(); 
         core.setAutoExecuting('" + event.index + "', false); }"},
    ]);
    ```
 - 延迟执行问题
   - 设置一个`core.status.event.data.appendingEvents`
   - 如果检测到延迟执行时，则将上述事件追加到这个列表中而不是直接`insertAction`
   - 当当前事件流完毕时`core.events._doAction_finishEvents`，若`appendingEvents`不为空，则将其第一个内容弹出并再插入事件流继续执行。

**Comment by zhaouv** [comment]
数据格式是
```
autoEvent:{
   '0,0:{
     '0':{...},
     '1':{...}
   },
}
```

**Comment by ckcz123** [comment]
每个自动事件的格式定义：
```js
{
"condition": "", // 条件不可为null
"currentFloor": false, // 是否仅在本层检测
"priority": 0, // 优先级
"delayExecuting": false, // 延迟执行
"executeOnce": false // 是否执行一次就销毁
"data": [], // 事件列表
}
```
