### ISSUE TITLE
h5样板多来点六毛钱的特效

### ISSUE THREAD

**Issue by ThinerDAS** [ckcz123/mota-js#409]
大家把适应于所有魔塔（主要是红海或者普通魔塔）的画面的设计、六毛钱特效跟在下面！：）

1、闪耀的动作
开启绚烂开关以后魔塔操作做得绚烂，参考3A大作，以下是例子：破墙打怪加上粉碎粒子效果，炸弹加上粒子效果和震撼效果（屏幕抖动、音效），飞时勇者移动到对应位置，拿宝物的时候声音清脆、宝物的图像从图块移动并缩小到屏幕左方能力值对应图标，移动到图标以后勇者对应图标像心跳一样渐变增大10%增大亮度50%持续0.2秒以后恢复原状。

2、怪物手册里对特殊属性用符文图标表示。这个已经有大量讨论，不细讲。

3、大黄门钥匙和地震卷轴，地图上的门和墙，同时破是可以的，但是也可以考虑在特效播放时，地图上的门墙以随机顺序先后破坏，像消消乐的大招一样。

4、模仿以前飞行员每击落一架敌机就在自己飞机上贴星星，在游戏界面的什么地方，放个栏，每打死一个怪物，把怪物的头像append到那个栏上。

5、（对于瞬间战斗和过程战斗都适用）战斗的时候，战斗前在游戏界面显示两行较宽的旗帜，一行的左边是怪物，另一行的右边是勇者，中间写VS。旗帜分别从左右进入画面，然后战斗、怪物消失以后旗帜从反方向离开画面。

6、中心对称飞行器使用时，中心对称飞行器动画从勇者相对中心的方向向中心方向飞行，盖住勇者的时候勇者消失，飞到对称位置的时候勇者出现，体现出一种“中心对称飞行器载着勇者飞过去”的效果。

7、楼传离开楼层和到达新楼层的时候体现出勇者从楼层中消失、出现在新楼层的渐变或跳跃效果。

8、圣水翻倍的时候勇者生命数字水平翻转，翻到中间的时候数值加倍，体现"翻"倍的效果。

9、勇者受到伤害的时候，勇者色调变红或变白闪一下，体现受到伤害。

10、领域等伤害显示出从怪物到勇者的随机路线的闪电效果；阻击可以是怪物向后退的同时，球形闪电以相同速度飞向勇者。

11、模仿ballance按空格提高视角，对大地图，按空格键缩小画面，使得更多的格子能显示在屏幕上；如果是小地图，那就把地图首尾相接，一屏能显示九个普通地图。

12、模仿竞速游戏的up主的屏幕，对于分阶段的魔塔，像分阶段的竞速游戏一样，每打一个boss，左面都会显示目前的成绩是否比参考成绩同期好、不好、N/A。

**Comment by user670** [comment]
> 3、大黄门钥匙和地震卷轴，地图上的门和墙，同时破是可以的，但是也可以考虑在特效播放时，地图上的门墙以随机顺序先后破坏，像消消乐的大招一样。

感觉按顺序（例如从上到下从左到右）也是可以的……

> 11、模仿ballance按空格提高视角，对大地图，按空格键缩小画面，使得更多的格子能显示在屏幕上；如果是小地图，那就把地图首尾相接，一屏能显示九个普通地图。

需要定义小地图的拼接关系。另，有了拼接关系后楼传/浏览地图的界面也能用得上吧。再另，有的塔好像（比方说）某张图的右边有两个出口接到两张不同的图，这样就不能/不便直接拼接地图了，不过可以画分离的地图再用连线表示出入口的对应？

**Comment by user670** [comment]
一些数值变化（例如拿宝石/血瓶/道具，打怪加金币）应该也可以画到勇士头顶上（不过如果勇士已经在画面最上的话会不会看不见）
