### ISSUE TITLE
虚拟键盘：这么多键都有用吗？

### ISSUE THREAD

**Issue by user670** [ckcz123/mota-js#55]
虚拟键盘上这么多键，但是好像只有快捷键相关的按键有用，诸如 Tab, CapsLock, Alt一类的键都没什么用吧（虽然不排除部分塔自定义部分快捷键的可能）。我觉得虚拟键盘上只需要有有用的键（相当于快捷菜单？），甚至可以将所有功能整合到正常的菜单里并抛弃虚拟键盘。（仍然注意可能有部分塔自定义快捷键！）

**Comment by ckcz123** [comment]
其实主要就是为了以后做技能塔方便，反正虚拟键盘都有了，不放白不放
