### ISSUE TITLE
关于core.js文件分解

### ISSUE THREAD

**Issue by i2Echo** [ckcz123/mota-js#60]
### 基本原则：
* core文件应该只保留最底层不依赖其他非原生模块或函数

### 目前core包含6部分
* 初始化部分，包括加载图片、音频、动画；开始游戏和重新开始游戏等
* 键盘、鼠标事件，包括onDown, onKeyDown等等
* 自动寻路部分，包括设置自动寻路，计算自动寻路
* 行走控制部分，包括设置自动行走，停止行走
* 地图和事件处理部分，包括获得某块，移除某块，添加全局动画，检查领域夹击事件等等
* 系统机制部分，包括表达式的计算、字符串切割、深拷贝对象、存读档、读取和下载文件等等

**Comment by ckcz123** [comment]
具体core.js的介绍参见：
https://ckcz123.github.io/mota-js/#/api

**Comment by i2Echo** [comment]
### 建议的大概分界(可以讨论再增减)
- app.js 入口（放初始化相关函数）
- HTMLActuator.js (执行相关dom操作)
- loader.js(负责文件加载相关操作)
- storage.js(负责储存相关)
- input.js(负责输入相关包括touch，键盘输入等)
- draw.js(绘制相关处理，已有，但是好像目前跟core存在相互依赖关系)
- core.js（为以上一些函数提供依赖，但是不要存在相互依赖关系）

**Comment by ckcz123** [comment]
从设计上来说，放在哪个文件就应该对应调用
比如，放在events文件就应该调用core.events.xxx
那如果这样分离的话，是否也需要例如 core.util.calValue 等？
还是类似insertAction，在core中设置转发
``` js
core.calValue = function (expression) {
    return core.utils.calValue(expression)
}
```

否则，可能需要修改的东西会非常多

**Comment by ckcz123** [comment]
另外关于动态加载的解耦合

``` js
function icons(t) {
    t.icons = new icons();
}

icons.prototype.xxx = ...
```

main先加载core.js文件；然后每加载一个其他文件如icons，则调用 `eval(name)(core)` 就行

**Comment by ckcz123** [comment]
个人想法：
core.js 为一切的入口，整个系统的核心（底层文件）。它自己不会做任何事情，只提供对其他文件的转发。
其他所有文件，包括actions.js, events.js, utils.js等等，都是互相独立的。在互相调用API时均需经过core.js转发。

即本质上：**core.js为一个interface。**

例如：
在core.js中定义core.insertAction（向当前事件列表插入若干自定义事件执行），并在events.js中写出其实现。那么，像在使用道具之类的效果时，都可以调用core.insertAction，它会被转发到events.js中。

![image](https://user-images.githubusercontent.com/8597348/36932322-60457cbe-1f02-11e8-97cd-06c8ef8fd0ec.png)
