### ISSUE TITLE
editor 的 z-index

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#66]
移除目前editor中的所有`z-index`  
目前的页面仅靠 **dom中靠后的元素渲染在上面** 足够满足  

mapColMark, mapRowMark, 以及右键菜单 `z-index:1`

blockly `z-index:10`

多行文本编辑器 `z-index:20`

同时这里的实现需要修改
``` html
      <div id="iconLib">
        <canvas class='egameCanvas' id='edata' width='416' height='416' style='z-index:0'></canvas>
        <div id="selectBox">
            <div id='dataSelection' v-show="isSelected" v-cloak></div>
        </div>
      </div>
```
在selectBox下面再增加一个空白canvas用来接收事件,即edata的事件改为由新增的canvas响应.移除
```
iconLib.onmousedown = function(e){
  e.stopPropagation();
}
```
虽然是同效果,但是这样的实现更为合理

**Comment by i2Echo** [comment]
### 关于移除z-index
意义不大，反正是css的东西，移除或者后面需要再添加都没啥影响
### 关于选择图片源
另外增加一个canvas没必要，要加的话随便一个div就够了；下面那句只是阻止事件冒泡而已，防止触发body绑定的取消选中事件，如果后面加个div覆盖确实就可以不用的，但是感觉都是无关痛痒的问题~~

**Comment by zhaouv** [comment]
使用canvas可以和[id=edata]一起设置宽高

z-index已经放到_server/README.md ,只要保持约定一致不造成混乱就行
