### ISSUE TITLE
可视化的地图编辑器

### ISSUE THREAD

**Issue by zhaouv** [ckcz123/mota-js#9]
## TODO

+ 标记没有ID的图块，或者给予警告  
+ 允许撤销一次
+ 重复图块的重定向
+ 导入数组形式的地图

<hr>

提供一个html5的可视化的界面来编辑地图 
(demo见评论)

通过一个简单的本地server来提供js的读写文件功能,网页通过post与之通信
(server的demo见评论)

约定见[issues/13](https://github.com/ckcz123/mota-js/issues/13)
<hr>

#### 初期目标

1. 写个html，能对地图可视化编辑。  
2. 地图可视化编辑器可以在线（http）或离线（file）协议运行。  
3. 不再从meaning.txt中读取，而是直接引入 icon.js 和 maps.js 读取对应关系。暂时不考虑直接修改libs中的文件（以后可能再会加上）  
4. 离线版只支持地图的编辑（数字和地图互转），在线版可以考虑传参（从现有的地图生成器传参）、或者直接获取剪切板图片进行生成。  

#### 更远期的计划
```
<script>main_mod='editer'</script>
<script src='main.js'></script>
```
能够直接以editer模式加载所有东西  
不显示动画音效  
但是heros之类的数据,图片都加载   
直接从main里取东西就行  
canvas也继续用main.core的canvas

**Comment by zhaouv** [comment]
[Newtonsoft.Json.dll.zip](https://github.com/ckcz123/mota-js/files/1566634/Newtonsoft.Json.dll.zip)

[demo.zip](https://github.com/ckcz123/mota-js/files/1566633/demo.zip)

**Comment by ckcz123** [comment]
读&写文件功能可以先放着，暂时是用不着的；如果之后要使用编辑器直接修改libs目录下的文件可以再用。

**Comment by zhaouv** [comment]
function readUTF8file(filename,callback){
	data={};
	data.name='readUTF8file';
	data.func='open';
	data.args=[String(filename)];
	postsomething(JSON.stringify(data),callback);
}
function writeUTF8file(filename,filestr,callback){
	data={};
	data.name='writeUTF8file';
	data.func='open';
	data.args=[String(filename),String(filestr)];
	postsomething(JSON.stringify(data),callback);
}

使用的js和css最好在html里面写好，不要单独拿出来（否则可能会造成误导，以为是和index.html相关的）也就是一个单文件

启动后是
http://127.0.0.1/常用目录/drawMapGUI.html
或者
file:///...../常用目录/drawMapGUI.html

直接从libs/icons.js和libs/maps.js中读取对应关系

仿照原来的写法,在不造成冲突的情况下，<script>引入js文件，只读，不改

比如定义一个参数main，main.instance.icons会被赋值为这个（在js引入时）
然后 main.instance.icons.getIcons() 就能获取对应关系了 

maps同理，不用关心其他各个函数，首先 main.instance.maps 会被赋值
直接对 id=1-300 调用 main.instance.maps.getBlock(0,0,id) 分别得到每个ID对应关系

直接调用getBlock，x和y简单的传0，id从1遍历到400，只有被定义过的ID才会返回event，得到id
 
不需要使用正则获取

如果用户画图时选择了没有被定义ID的项目，则提示用户“该ID未被定义！ 

maps ----> 获取数字和ID的对应关系
icons ----> 获取ID和图标位置的对应关系
两相结合，就能得到数字和图标的对应关系了

**Comment by ckcz123** [comment]
drawMapGUI.html 放在根目录下（和index.html同级），这样不管是 file 协议还是 http 协议，路径地址都是统一的

**Comment by i2Echo** [comment]
TODO：更新布局已完成 #12

**Comment by ckcz123** [comment]
TODO 新加：
类似地图生成器一样把编辑框给出来，使得用户可以粘贴JSON到编辑框中，并一键生成现有的地图。（从而能对已经存在的地图进行编辑）
值得注意的是，编辑框中的内容最好能格式化（对齐、空格、trim等等）
